"use client";
import { Component, lazy, Suspense, useCallback, useEffect, useRef, useState, type ReactNode } from "react";
import { chapters, objects, legacyTopics, sources, agentSteps, type ObjectId, type ViewId } from "./content";
import "./studio.css";
const Canvas=lazy(()=>import("./StudioCanvas"));
class SceneBoundary extends Component<{children:ReactNode;retry:()=>void},{failed:boolean}>{state={failed:false};static getDerivedStateFromError(){return {failed:true};}render(){return this.state.failed?<div className="studio-fallback"><h2>文字でスタジオを探索</h2><p>3Dの読み込みに失敗しました。章と参考資料は引き続き使えます。</p><button onClick={()=>{this.setState({failed:false});this.props.retry();}}>再読み込み</button></div>:this.props.children;}}
const choices=[{name:"ひと息つく",symbol:"◒",title:"余白を、一つ。",message:"少しだけ手を止めて、窓の外を見てみる。次のアイデアは、そのあとで。"},{name:"新しく始める",symbol:"✳",title:"小さな一歩。",message:"気になっていたことを、一つだけ形に。完成よりも、まず試してみる。"},{name:"見方を変える",symbol:"◇",title:"違う角度から。",message:"いつものものを、別の人の目で眺めてみる。何が見えてきますか。"}];
const format=(seconds:number)=>`${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,"0")}`;
export default function Studio(){
  const [chapter,setChapter]=useState(0),[mode,setMode]=useState<"guide"|"explore">("guide"),[overview,setOverview]=useState(true),[reference,setReference]=useState(false),[referencePage,setReferencePage]=useState<string|null>(null),[query,setQuery]=useState(""),[category,setCategory]=useState("すべて");
  const [index,setIndex]=useState(false),[notes,setNotes]=useState(false),[elapsed,setElapsed]=useState(0),[timer,setTimer]=useState(false),[step,setStep]=useState(0),[playing,setPlaying]=useState(false),[board,setBoard]=useState(0),[theme,setTheme]=useState(0),[drawn,setDrawn]=useState(false),[flipped,setFlipped]=useState(false),[review,setReview]=useState(0),[process,setProcess]=useState(0),[skip,setSkip]=useState(0),[reveal,setReveal]=useState(false),[ready,setReady]=useState(false),[sceneKey]=useState(0);
  const [profile,setProfile]=useState({name:"王 博",romanName:"WANG BO",currentTeam:"シス１ × Multi Beam",joinYear:"2023～",joinTitle:"ハイテクへ中途入社",currentYear:"2025～",currentTitle:"Multi Beamチーム"});
  const dialog=useRef<HTMLDialogElement>(null),notesDialog=useRef<HTMLDialogElement>(null),lastFocus=useRef<HTMLElement|null>(null),title=useRef<HTMLHeadingElement>(null),revealTimeout=useRef<ReturnType<typeof setTimeout>|null>(null);
  const c=chapters[chapter],view:ViewId=overview?"room":c.view;
  useEffect(()=>{try{const p=JSON.parse(localStorage.getItem("gen-ai-profile-v1")||"null");if(p)setProfile(old=>({...old,...p}));const saved=JSON.parse(sessionStorage.getItem("work-studio-v2")||"null");if(saved){setChapter(Math.max(0,Math.min(7,Number(saved.chapter)||0)));setMode(saved.mode==="explore"?"explore":"guide");setOverview(true);setStep(Math.max(0,Math.min(6,Number(saved.step)||0)));setTheme(Math.max(0,Math.min(2,Number(saved.theme)||0)));setDrawn(!!saved.drawn);setFlipped(!!saved.flipped);setReview(Number(saved.review)&7);setElapsed(Number(saved.elapsed)||0);}}
    catch{/* Storage may be disabled; the presentation still works. */}setReady(true);
    const oldSlide=new URLSearchParams(location.search).get("slide");if(oldSlide){setReferencePage(oldSlide);setReference(true);}
  },[]);
  useEffect(()=>{if(!ready)return;try{sessionStorage.setItem("work-studio-v2",JSON.stringify({chapter,mode,overview,step,theme,drawn,flipped,review,elapsed}));}catch{}},[ready,chapter,mode,overview,step,theme,drawn,flipped,review,elapsed]);
  useEffect(()=>{if(!timer||reference)return;const id=setInterval(()=>setElapsed(s=>s+1),1000);return()=>clearInterval(id);},[timer,reference]);
  useEffect(()=>{if(!playing||chapter!==4||reference||overview)return;const id=setInterval(()=>setStep(s=>{if(s>=6){setPlaying(false);return 6;}return s+1;}),2400);return()=>clearInterval(id);},[playing,chapter,reference,overview]);
  useEffect(()=>{if(reference){lastFocus.current=document.activeElement as HTMLElement;dialog.current?.showModal();}else{dialog.current?.close();lastFocus.current?.focus();try{const p=JSON.parse(localStorage.getItem("gen-ai-profile-v1")||"null");if(p)setProfile(old=>({...old,...p}));}catch{}}},[reference]);
  useEffect(()=>{if(notes)notesDialog.current?.showModal();else notesDialog.current?.close();},[notes]);
  useEffect(()=>()=>{if(revealTimeout.current)clearTimeout(revealTimeout.current);},[]);
  const go=useCallback((n:number)=>{const next=Math.max(0,Math.min(7,n));setChapter(next);setOverview(next===2);setIndex(false);setPlaying(false);setReveal(false);requestAnimationFrame(()=>{title.current?.focus({preventScroll:true});const panel=title.current?.closest(".studio-copy");if(panel)panel.scrollTop=0;const nav=document.querySelector<HTMLElement>(".studio-route"),active=nav?.querySelector<HTMLElement>("[aria-current=step]");if(nav&&active)nav.scrollLeft=active.offsetLeft-nav.offsetLeft-nav.clientWidth/2+22;});},[]);
  const openReference=useCallback(()=>{setReference(true);setPlaying(false);},[]);
  const select=useCallback((id:ObjectId)=>{if(id==="library"){openReference();return;}if(!overview&&id===c.view){if(id==="cards"){if(!drawn)setDrawn(true);else setFlipped(true);}if(id==="board")setBoard(b=>(b+1)%3);if(id==="monitor"){setPlaying(false);setStep(s=>(s+1)%7);}return;}go(objects.find(o=>o.id===id)!.chapter);},[go,openReference,overview,c.view,drawn]);
  const closeReference=()=>{setReference(false);setReferencePage(null);};
  useEffect(()=>{const key=(e:KeyboardEvent)=>{if(reference||notes||e.defaultPrevented||(e.target as HTMLElement).closest("input,textarea,select,[contenteditable=true]"))return;if(e.key==="Escape"){setOverview(true);setIndex(false);setPlaying(false);return;}if((e.target as HTMLElement).closest("button,a,summary"))return;if(e.key==="ArrowRight"||e.key==="ArrowDown"){e.preventDefault();go(chapter+1);}if(e.key==="ArrowLeft"||e.key==="ArrowUp"){e.preventDefault();go(chapter-1);}if(e.key==="Escape"){setOverview(true);setPlaying(false);}if(e.key==="Enter"&&overview){e.preventDefault();go(chapter===2?3:chapter);}};window.addEventListener("keydown",key);return()=>window.removeEventListener("keydown",key);},[chapter,go,reference,notes,overview]);
  const enterStudio=()=>{go(2);setReveal(true);if(revealTimeout.current)clearTimeout(revealTimeout.current);revealTimeout.current=setTimeout(()=>setReveal(false),2600);};
  const stageNames=["Idea","Design","Build","Try","Improve"];
  const stageDescriptions=["目標は「問いを入力し、カードを引いて結果を見る」。旧版に記された体験の起点。","操作の順序、カードの見え方、読みやすさを設計する。","AIが画面やコードの案を補い、最小の体験をつなぐ。","押す → 裏返す → 読む → もう一度。手元の操作から確かめる。","分かりにくさを言葉にし、実装へ戻す。実際の変更履歴は未提供。"];
  return <main className="work-studio" data-chapter={chapter} data-mode={mode} data-ready={ready} data-overview={overview} data-view={view}>
    <div className="studio-app" inert={reference||notes}>
    <header className="studio-header">
      <a href="/" className="studio-brand" aria-label="スタジオの全景に戻る" onClick={e=>{e.preventDefault();setOverview(true);setPlaying(false);setIndex(false);}}><span className="studio-monogram">w<span>.</span></span><span>WANG BO<small>INTERACTIVE WORK STUDIO</small></span></a>
      <div className="studio-header-actions"><button className="studio-menu" aria-label="参考資料" onClick={openReference}>Archive <span>↗</span></button><button className="studio-index-toggle" aria-expanded={index} aria-controls="studio-index" onClick={()=>setIndex(v=>!v)}>Index <span>{index?"−":"+"}</span></button></div>
    </header>
    {index&&<nav id="studio-index" className="studio-index" aria-label="章を選ぶ"><div className="studio-index-head"><span>EXPLORE THE STUDIO</span><button onClick={()=>setIndex(false)} aria-label="目次を閉じる">×</button></div><div className="studio-mode" role="group" aria-label="表示モード"><button aria-pressed={mode==="guide"} onClick={()=>setMode("guide")}>10分ガイド</button><button aria-pressed={mode==="explore"} onClick={()=>setMode("explore")}>自由探索</button></div>{chapters.map((ch,i)=><button className="studio-index-chapter" key={ch.title} aria-label={`${i+1} ${ch.title}`} aria-current={chapter===i?"step":undefined} onClick={()=>go(i)}><small>{String(i+1).padStart(2,"0")}</small><span>{ch.title}</span><b>↗</b></button>)}<button className="studio-presenter" aria-label="講者モードを開く" onClick={()=>{setIndex(false);setNotes(true);}}>講者メモ・タイマー ↗</button></nav>}
    <div className={`studio-body ${chapter===4||chapter===5?"studio-interactive":""}`}>
    {!overview&&<section key={chapter} className={`studio-copy studio-content-${view}`} aria-label="現在の章"><button className="studio-content-close" aria-label="閉じて全景に戻る" onClick={()=>{setOverview(true);setPlaying(false);}}>×</button>
      <div className="studio-chapter-kicker"><span>{String(chapter+1).padStart(2,"0")} <i>/</i> 08</span><span>{c.en}</span></div>
      <h1 ref={title} tabIndex={-1}>{c.question.split("\n").map((line,i)=><span key={line}>{line}{i===0&&<br/>}</span>)}</h1>
      <p className="studio-standfirst">{c.point}</p>
      {chapter===0?<><div className="studio-profile"><div className="studio-profile-mark">王</div><div><h2>{profile.name}<small>{profile.romanName}</small></h2><p>{profile.currentTeam}</p></div></div><div className="studio-career"><p><b>{profile.joinYear}</b>{profile.joinTitle}</p><p><b>{profile.currentYear}</b>{profile.currentTitle}を兼務</p></div><p className="studio-intro-line">今日は、私がAIとつくる日々を。<br/>小さな気づきから、手元で動く作品まで。</p><button className="studio-primary" onClick={()=>go(1)}>最近、取り組んでいること <span>↗</span></button><small className="studio-footnote">実際のオフィスを再現したものではなく、<br/>日々の制作を表す、抽象化したワークスタジオです。</small></>:
      <>{chapter===1&&<ul className="studio-points">{c.bullets.map((b,i)=><li key={b}><span>0{i+1}</span>{b}</li>)}</ul>}
      {chapter===1&&<><div className="studio-note"><small>ON MY MIND</small><p>「こんなものがあったら」を、<br/>メモのままで終わらせない。</p><span>Codex · Coding Agent · 試作</span></div><button className="studio-primary" onClick={enterStudio}>スタジオへ <span>↗</span></button></>}
      {chapter===2&&<div className="studio-room-invite"><span className="studio-spark">✳</span><p>気になるものを<br/>クリックしてみてください。</p><button onClick={()=>go(3)}>研究ボードから始める →</button></div>}
      {chapter===3&&<><div className="studio-board-tabs" role="group" aria-label="研究ボードの項目">{["LLM","Tool Use","Agent"].map((b,i)=><button key={b} aria-pressed={board===i} onClick={()=>setBoard(i)}>{b}</button>)}</div><p className="studio-board-explanation" aria-live="polite">{["文脈から推論・生成する。文章を出すことと、外部を操作することは別。","モデルが操作を要求し、システムがツールを実行する。結果を次へ返す。","目標と結果に応じて行動を選ぶ。Workflowと組み合わせて使える。"][board]}</p><details className="studio-details"><summary>仕事の進め方を変えた、2つの公開例</summary><p className="studio-footnote">確認日：2026-09-28 · 最新情報の網羅ではありません</p>{sources.slice(0,2).map(s=><article key={s.title}><time>{s.date}</time><a href={s.url} target="_blank" rel="noreferrer">{s.title} ↗</a><p>{s.note}</p></article>)}</details></>}
      {chapter===4&&<div className="studio-agent"><div className="studio-demo-label"><i/> 仕組みのデモ <span>AI未接続</span></div><div className="studio-step-track" aria-label="Agentの工程">{agentSteps.map((s,i)=><button key={i} title={s.title} aria-label={`${i+1} ${s.title}`} aria-current={step===i?"step":undefined} onClick={()=>{setPlaying(false);setStep(i);}}><span>{i+1}</span><small>{s.phase}</small></button>)}</div><div className="studio-step-text" aria-live="polite"><strong>{agentSteps[step].title}</strong><p>{agentSteps[step].action}</p></div><div className="studio-viewport-label"><span>実際のHTMLプレビュー</span><span>320px</span></div><div className="studio-mini-viewport" data-broken={agentSteps[step].broken}><span className="studio-mini-card">✦</span><strong>今日の、一枚。</strong><div className={`studio-example-button ${agentSteps[step].broken?"is-broken":""}`}>カードをひく <span>→</span></div>{agentSteps[step].broken&&<span className="studio-overflow-mark">はみ出し →</span>}</div><details className="studio-code"><summary>{agentSteps[step].file} · 変更 / チェックを見る</summary><pre>{agentSteps[step].code}</pre></details><div className="studio-demo-controls"><button aria-label="前のステップ" disabled={step===0} onClick={()=>{setPlaying(false);setStep(s=>s-1);}}>←</button><button disabled={step===6&&!playing} onClick={()=>setPlaying(v=>!v)}>{playing?"一時停止":"再生"}</button><button disabled={step===6} onClick={()=>{setPlaying(false);setStep(s=>s+1);}}>次のステップ →</button><button aria-label="Agentデモをリセット" onClick={()=>{setPlaying(false);setStep(0);}}>↺</button></div><details className="studio-details"><summary>MCP・Harness・Loopの役割</summary><p><b>MCP</b> — ツールと文脈の接続。計画や安全を自動では保証しない。</p><p><b>Harness</b> — 情報、状態、ツール、実行環境、検証を支える。</p><p><b>Loop</b> — 行動、観察、判断、再計画または停止。Harnessとの範囲は実装による。</p><p>AgentにMCPやRAGは必須ではありません。</p><button onClick={()=>{setReferencePage("mcp");openReference();}}>原資料で詳しく →</button></details></div>}
      {chapter===5&&<div className="studio-daycard"><div className="studio-demo-label"><i/> DAY CARD <span>ローカル軽量デモ</span></div><div className="studio-theme" role="group" aria-label="カードのテーマ">{choices.map((t,i)=><button key={t.name} disabled={drawn} aria-pressed={theme===i} onClick={()=>setTheme(i)}>{t.name}</button>)}</div><button className={`studio-play-card ${flipped?"is-flipped":""}`} data-drawn={drawn} disabled={!drawn||flipped} aria-label={flipped?"カードの結果":drawn?"カードを裏返す":"カードはまだ引いていません"} onClick={()=>setFlipped(true)}><span className="studio-card-back"><small>A LITTLE PAUSE</small><b>✳</b><em>DAY CARD</em><span>{drawn?"クリックして、裏返す":"今日の、一枚。"}</span></span><span className="studio-card-front"><b>{choices[theme].symbol}</b><strong>{choices[theme].title}</strong><span>{choices[theme].message}</span></span></button><div className="studio-card-actions"><button className="studio-primary" onClick={()=>{if(drawn){setDrawn(false);setFlipped(false);}else{setDrawn(true);setProcess(3);}}}>{drawn?"もう一度ひく":"一枚、ひいてみる"} <span>{drawn?"↺":"↗"}</span></button><a href="https://www.daycard.site/" target="_blank" rel="noreferrer" title="2026-09-28確認：HTTP 404">元のURL（現在404）↗</a></div><div className="studio-process" role="group" aria-label="制作の5工程">{stageNames.map((name,i)=><button key={name} aria-pressed={process===i} onClick={()=>setProcess(i)}>{name}</button>)}</div><p className="studio-process-text">{stageDescriptions[process]}</p><details className="studio-details"><summary>元作品と、このデモについて</summary><p>旧版の体験目標をもとに再構成した説明用デモです。元作品の変更前後・会話履歴・制作時間は未検証。実際の改善履歴としては扱いません。</p><a href="/studio/daycard-original.png" target="_blank">旧版に残るDay Cardの紹介画面 ↗<img src="/studio/daycard-original.png" alt="旧版プロジェクトに残っていたDay Cardの紹介画面。制作時間の主張は未検証。" className="studio-archive-thumb" /></a><p className="studio-footnote">旧プロジェクトに残る画面記録。原作品URLは2026-09-28の確認でHTTP 404。復旧するまで、ここではローカル体験をご利用ください。</p></details></div>}
      {chapter===6&&<><div className="studio-checklist">{["操作の流れを確認する","読みやすさを確認する","公開内容の根拠を確認する"].map((text,i)=><label key={text}><input type="checkbox" checked={!!(review&(1<<i))} onChange={()=>setReview(r=>r^(1<<i))}/><span>{text}</span></label>)}</div><div className="studio-review-preview" data-clear={!!(review&2)}><small>作品の確認イメージ</small><p>{review&1?"ひく → 読む → もう一度":"次の操作は…？"}</p><span>{review&4?"出典・公開範囲を表示 ✓":"出典・公開範囲は未確認"}</span><b>{review===7?"人のレビューへ →":"確認したことを、作品に反映。"}</b></div><p className="studio-footnote">チェックと表示変化は説明用。実端末や実データの検証を代替しません。</p></>}
      {chapter===7&&<><div className="studio-closing"><span>✳</span><p>日常の小さな気づきが、<br/>次の作品のはじまり。</p><small>THANK YOU FOR VISITING.</small></div><button className="studio-primary" onClick={()=>{setMode("explore");setOverview(true);}}>自由に探索する <span>↗</span></button><button className="studio-text-button" onClick={openReference}>技術の続きは、資料棚へ →</button></>}
      </>}
    </section>}
    <section className="studio-stage" aria-label="3Dスタジオ"><SceneBoundary key={sceneKey} retry={()=>window.location.reload()}><Suspense fallback={<div className="studio-loading">スタジオを準備しています…</div>}><Canvas view={view} chapter={chapter} paused={reference||notes} cardOpen={chapter===5&&drawn&&!overview} boardStep={board} review={review} onSelect={select} skipToken={skip} agentStep={step} flipped={flipped} cardTheme={theme}/></Suspense></SceneBoundary>{reveal&&<button className="studio-skip" onClick={()=>{setSkip(n=>n+1);setReveal(false);}}>移動をスキップ →</button>}</section>
    </div>
    <footer className="studio-footer">
      <div className="studio-location"><span className="studio-live-dot"/><span>{overview?"THE STUDIO":c.en}</span><small>{overview?"MAKE · TRY · IMPROVE":String(chapter+1).padStart(2,"0")+" / 08"}</small></div>
      {overview?<button className="studio-tour-start" onClick={()=>go(chapter===0?0:Math.min(chapter+1,7))}>{chapter===0?"10分のストーリーをたどる":"ストーリーの続きを見る"}<span>↗</span></button>:<div className="studio-navigation"><button aria-label="全景に戻る" onClick={()=>{setOverview(true);setPlaying(false);}}>⌂</button><button aria-label="前の章" disabled={chapter===0} onClick={()=>go(chapter-1)}>←</button><span>{String(chapter+1).padStart(2,"0")} / 08</span><button aria-label="次の章" disabled={chapter===7} onClick={()=>chapter===1?enterStudio():go(chapter+1)}>→</button></div>}
    </footer>
    {overview&&<div className="studio-explore-hint"><span>＋</span> 気になるものに、触れてみる。</div>}
    <div className="studio-sr" aria-live="polite">第{chapter+1}章 {c.title}。{overview?"全景を表示中。":""}</div>
    </div>
    <dialog ref={dialog} className="studio-library-dialog" onKeyDown={e=>{if(e.key==="Escape"){e.preventDefault();closeReference();}}} onCancel={e=>{e.preventDefault();closeReference();}}><div className="studio-dialog-top"><div><span>THE REFERENCE SHELF</span><h2>参考資料 / フルバージョン</h2></div><button onClick={closeReference} aria-label="資料を閉じて元の章に戻る">元の章に戻る ×</button></div>{reference&&<>{referencePage?<><div className="studio-archive-bar"><button onClick={()=>setReferencePage(null)}>← 目次へ</button><p>原文を保持した旧版 · 編集・並べ替えも利用できます</p><a href={`/reference/?slide=${encodeURIComponent(referencePage)}`} target="_blank" rel="noreferrer">別タブ ↗</a></div><iframe key={referencePage} title="旧版フルバージョン" src={`/reference/?slide=${encodeURIComponent(referencePage)}`} className="studio-legacy-frame"/></>:<div className="studio-library-content"><p>全24ページを原文のまま保存。10分ガイドで扱わない年表・MCP・三層モデルも、ここから。制作時間など旧版の表現は当時の記述であり、検証済みの実績を意味しません。</p><div className="studio-library-search"><input type="search" aria-label="資料を検索" placeholder="テーマを探す：MCP、Agent、制作…" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="資料の分類" value={category} onChange={e=>setCategory(e.target.value)}>{["すべて","個人","背景","仕組み","制作","検証","出典"].map(v=><option key={v}>{v}</option>)}</select></div><div className="studio-library-grid">{legacyTopics.filter(([,label,cat])=>(category==="すべて"||cat===category)&&label.toLowerCase().includes(query.toLowerCase())).map(([id,label,cat],i)=><button onClick={()=>setReferencePage(id)} key={id}><small>{cat}</small><span>{label}</span><b>{String(i+1).padStart(2,"0")} ↗</b></button>)}</div>{!legacyTopics.some(([,label,cat])=>(category==="すべて"||cat===category)&&label.toLowerCase().includes(query.toLowerCase()))&&<p>一致する資料がありません。別の言葉で検索してください。</p>}<div className="studio-source-list"><h3>このガイドの根拠</h3><p>確認日：2026-09-28 · 公開年月と、資料を確認した日を区別しています。</p>{sources.map(s=><a href={s.url} key={s.title} target="_blank" rel="noreferrer"><time>{s.date}</time><b>{s.title} ↗</b><span>{s.note}</span></a>)}<a href="/studio/source-audit.json" target="_blank"><b>旧版51件のリンク確認記録 ↗</b><span>到達確認と内容の検証を区別。未確認の記述は新しい主線に使用していません。</span></a><a href="/studio/発表原稿_日本語.md" target="_blank">旧版の日本語講稿 ↗</a><a href="/studio/原稿.md" target="_blank">旧版原稿 ↗</a><a href="/atlas/" target="_blank">旧版の独立3D Atlas ↗</a></div></div>}</>}</dialog>
    <dialog ref={notesDialog} className="studio-notes-dialog" onCancel={()=>setNotes(false)}><div className="studio-dialog-top"><div><span>PRESENTER NOTES · 画面共有時は閉じてください</span><h2>{String(chapter+1).padStart(2,"0")} {c.title}</h2></div><button onClick={()=>setNotes(false)}>閉じる ×</button></div><div className="studio-notes-content"><div className="studio-notes-clock"><b>{format(elapsed)}</b><span>全体の経過 / 目標 10:00<br/>この章の目安 {c.time}秒（操作込み）</span><button onClick={()=>setTimer(v=>!v)}>{timer?"計時を停止":"計時を開始"}</button><button onClick={()=>{setTimer(false);setElapsed(0);}}>リセット</button></div><p className="studio-script">{c.script}</p><div className="studio-next-cue"><small>次の操作</small><p>{c.next}</p></div><p className="studio-footnote">発表者の操作で進行します。自動で章は切り替わりません。原資料：{c.old.join(" / ")}</p><div className="studio-demo-controls"><button disabled={chapter===0} onClick={()=>go(chapter-1)}>← 前の章</button><button disabled={chapter===7} onClick={()=>go(chapter+1)}>次の章 →</button></div></div></dialog>
  </main>;
}

