// Run against the local preview: node tests/interactions.test.mjs
import assert from 'node:assert/strict';
import { mkdir, writeFile } from 'node:fs/promises';
const { chromium } = await import(process.env.PLAYWRIGHT_MODULE || 'playwright');
const browser = await chromium.launch({headless:true,...(process.env.PLAYWRIGHT_CHANNEL?{channel:process.env.PLAYWRIGHT_CHANNEL}:{})});
const context = await browser.newContext({viewport:{width:1600,height:1000},reducedMotion:'no-preference'});
const page = await context.newPage();
const errors=[], results=[], layouts=[];
page.on('pageerror',error=>errors.push(error.message));
await mkdir('outputs/direct-review',{recursive:true});
const base = process.env.DECK_URL || 'http://127.0.0.1:5173/reference/';
await page.goto(base,{waitUntil:'networkidle',timeout:60000});
await page.waitForFunction(()=>document.querySelector('#presentation').dataset.ready==='true');
const section=id=>page.locator(`section[data-slide-id="${id}"]`);
async function go(id) {
 await page.evaluate(id=>{const s=document.querySelector(`section[data-slide-id="${id}"]`); s.scrollTop=0; document.querySelector('#presentation').scrollTop=s.offsetTop;},id);
 await page.waitForFunction(id=>document.querySelector('#presentation').dataset.currentSlide===id,id);
}
async function check(name,fn) { try { await fn(); results.push({name,pass:true}); console.log('PASS '+name); } catch(error) { results.push({name,pass:false,error:error.message}); console.log('FAIL '+name+' '+error.message.slice(0,300)); } }
const has=async (locator,text)=>{await locator.filter({hasText:text}).waitFor({state:'attached'});assert.ok((await locator.textContent()).includes(text),`Expected ${text}`);};
const pressed=async locator=>assert.equal(await locator.getAttribute('aria-pressed'),'true');
const click=async (id,name)=>section(id).getByRole('button',{name,exact:true}).click();
await check('default 18 pages, visible native pointer, optional laser',async()=>{
 assert.equal(await page.locator('section[data-slide-id]:not([hidden])').count(),18);
 assert.notEqual(await section('intro').evaluate(e=>getComputedStyle(e).cursor),'none');
 assert.equal(await page.getByRole('button',{name:'次のページ',exact:true}).evaluate(e=>getComputedStyle(e).cursor),'pointer');
 await page.getByRole('button',{name:'レーザーポインター',exact:true}).click(); await page.mouse.move(600,300);
 await page.waitForFunction(()=>getComputedStyle(document.querySelector('.ambient-cursor')).display==='block');
 assert.notEqual(await section('intro').evaluate(e=>getComputedStyle(e).cursor),'none');
 await page.getByRole('button',{name:'レーザーポインター',exact:true}).click();
 assert.equal(await page.locator('.ambient-cursor').evaluate(e=>getComputedStyle(e).display),'none');
});
await page.evaluate(()=>localStorage.setItem('gen-ai-slide-settings-v2',JSON.stringify({hidden:[]})));
await page.reload({waitUntil:'networkidle'});
await page.waitForFunction(()=>document.querySelectorAll('section[data-slide-id]:not([hidden])').length===20);
await check('01 career selection',async()=>{await go('intro'); await section('intro').locator('.career-year').nth(1).click(); await has(section('intro').locator('.career-focus'),'ハイテク'); assert.equal(await section('intro').locator('.profile-identity').getAttribute('data-career-focus'),'1');});
await check('02 cover layers and replay',async()=>{await go('cover');await click('cover','SYSTEM');await has(section('cover').locator('figcaption'),'Context');await click('cover','三層の組み立てを再生');});
await check('03 cumulative capabilities',async()=>{await go('manifesto');await click('manifesto','＋タスク実行');await has(section('manifesto').locator('.lab-result'),'人の確認');});
await check('04 3D overview, node details and keyboard isolation',async()=>{await go('overview');await section('overview').locator('.atlas-visual[data-status="ready"]').waitFor();await click('overview','LLMの詳細');await page.locator('.atlas-holo-card').waitFor();await page.keyboard.press('ArrowRight');assert.equal(await page.locator('#presentation').getAttribute('data-current-slide'),'overview');await page.keyboard.press('Escape');await page.waitForSelector('.atlas-holo-card',{state:'hidden'});});
await check('05 chronology, pin comparison and phase filter',async()=>{await go('timeline');await click('timeline','比較に固定');await section('timeline').locator('.chronology-rail button').nth(10).click();await has(section('timeline').locator('.chronology-card'),'MCP');await has(section('timeline').locator('.chronology-pinned'),'Transformer');await section('timeline').locator('.scene-tabs').getByRole('button',{name:'接続',exact:true}).click();assert.equal(await section('timeline').locator('.chronology-rail button').count(),1);await click('timeline','比較を閉じる');assert.equal(await section('timeline').locator('.chronology-pinned').count(),0);});
await check('06 reasoning failure, revision, strict-budget pass',async()=>{await go('reasoning');await click('reasoning','上限2万円');for(let i=0;i<2;i++)await click('reasoning','1ステップ →');await has(section('reasoning').locator('.lab-result'),'FAIL');for(let i=0;i<3;i++)await click('reasoning','1ステップ →');await has(section('reasoning').locator('.lab-result'),'PASS');await has(section('reasoning').locator('.lab-result'),'20,000');});
await check('07 media changes actual scene, opt-in audio and pause',async()=>{await go('media');await click('media','TEXT');await has(section('media').locator('.media-typeset'),'静かな湖');await click('media','IMAGE');assert.equal(await section('media').locator('.landscape').count(),1);await click('media','昼夜を切り替え');assert.equal(await section('media').locator('.media-screen').getAttribute('data-night'),'false');await click('media','AUDIO');const audio=section('media').locator('audio');assert.equal(await audio.evaluate(e=>e.paused),true);await click('media','音を再生');await page.waitForFunction(()=>!document.querySelector('[data-slide-id="media"] audio').paused);await go('open-local');assert.equal(await audio.evaluate(e=>e.paused),true);await go('media');await click('media','VIDEO');await section('media').getByRole('slider').fill('120');await has(section('media').locator('.media-overlay'),'10 : 10');});
await check('08 packet routing obeys data and network boundaries',async()=>{await go('open-local');await click('open-local','Cloudで処理');await page.waitForFunction(()=>document.querySelector('.cloud-map').dataset.status==='COMPLETE');await has(section('open-local').locator('.scene-metrics'),'CLOUD');await click('open-local','◇ 公開情報');await click('open-local','Cloudで処理');await page.waitForFunction(()=>document.querySelector('.cloud-map').dataset.status==='BLOCKED');await has(section('open-local').locator('.network-output'),'DATA BOUNDARY');await click('open-local','Localで処理');await page.waitForFunction(()=>document.querySelector('.cloud-map').dataset.status==='COMPLETE');await click('open-local','GPU ON');await click('open-local','Localで処理');await page.waitForFunction(()=>document.querySelector('.cloud-map').dataset.status==='BLOCKED');await has(section('open-local').locator('.network-output'),'GPU UNAVAILABLE');});
await check('09 controllers follow distinct recovery routes and pause',async()=>{await go('agent');await click('agent','APIエラー');for(let i=0;i<12;i++)await click('agent','次のステップ');await has(section('agent').locator('.controller-artifact').nth(2),'保存状態を確認');await has(section('agent').locator('.controller-artifact').nth(1),'上限で停止');await click('agent','リセット');await click('agent','再生');await page.waitForTimeout(400);await go('mcp');const before=await section('agent').locator('.scene-playback output').textContent();await page.waitForTimeout(700);assert.equal(await section('agent').locator('.scene-playback output').textContent(),before);await go('agent');assert.equal(await section('agent').getByRole('button',{name:'再生',exact:true}).getAttribute('aria-pressed'),'false');});
await check('10 MCP wires connect, carry packets and disconnect',async()=>{await go('mcp');await section('mcp').locator('.protocol-servers button').nth(2).dragTo(section('mcp').locator('.protocol-host'));await pressed(section('mcp').locator('.protocol-servers button').nth(2));assert.equal(await section('mcp').locator('.protocol-wire.connected').count(),3);await click('mcp','MCPリクエストを送る');await has(section('mcp').locator('.protocol-packet'),'lookup_route');await has(section('mcp').locator('.protocol-packet'),'14,000 JPY');await section('mcp').locator('.protocol-servers button').nth(2).click();assert.equal(await section('mcp').getByRole('button',{name:'MCPリクエストを送る',exact:true}).isDisabled(),true);});
await check('11 module switches change grounded and actionable output',async()=>{await go('concepts');await click('concepts','RAG');await click('concepts','MCP');await click('concepts','AGENT');await click('concepts','出張申請を実行');await has(section('concepts').locator('.concept-receipt'),'SINGLE RESPONSE');await has(section('concepts').locator('.concept-receipt'),'申請文');await has(section('concepts').locator('.concept-receipt'),'出典 —');await click('concepts','RAG');await click('concepts','MCP');await click('concepts','AGENT');await click('concepts','出張申請を実行');await has(section('concepts').locator('.concept-receipt'),'DRAFT-042');await has(section('concepts').locator('.concept-receipt'),'VERIFIED');});
await check('12 precise prompt, loading and duplicate handling',async()=>{await go('vibe');await click('vibe','受入条件を明記');await section('vibe').getByLabel('処理中の状態を試す').check();assert.equal(await section('vibe').getByRole('button',{name:'下書きを準備中…',exact:true}).isDisabled(),true);await section('vibe').getByLabel('処理中の状態を試す').uncheck();await section('vibe').getByLabel('キーボード条件を表示').check();await section('vibe').getByRole('button',{name:'下書きを作成',exact:true}).press('Enter');await has(section('vibe').locator('.vibe-preview output'),'DRAFT-042');assert.equal(await section('vibe').getByRole('button',{name:'下書きを作成しました',exact:true}).isDisabled(),true);});
await check('13 cost reduction and reinvestment balance',async()=>{await go('commodity');await section('commodity').getByRole('slider').fill('50');const values=await section('commodity').locator('.cost-equation > div > b').allTextContents();assert.deepEqual(values,['100','70']);await section('commodity').locator('.investment-targets button').nth(2).click();await has(section('commodity').locator('.investment-targets button').nth(2),'＋30');const work=(await section('commodity').locator('.cost-factory').nth(1).locator('.cost-block b').allTextContents()).reduce((a,v)=>a+Number(v),0);assert.equal(work+30,100);});
await check('14 architecture rotates, separates and selects layers',async()=>{await go('engineering');await click('engineering','2D');assert.equal(await section('engineering').locator('.architecture-viewport').getAttribute('data-flat'),'true');await section('engineering').locator('.architecture-board').nth(3).click();await has(section('engineering').locator('.architecture-inspector'),'LOOP');await click('engineering','3D');const viewport=section('engineering').getByRole('button',{name:'設計層の視点',exact:true});await viewport.focus();await viewport.press('ArrowRight');assert.equal(await section('engineering').locator('.architecture-assembly').evaluate(e=>e.style.getPropertyValue('--rz')),'-23deg');assert.equal(await page.locator('#presentation').getAttribute('data-current-slide'),'engineering');});
await check('15 permission failure stops, retry branch recovers',async()=>{await go('harness');await click('harness','権限がない');for(let i=0;i<5;i++)await click('harness','1ステップ →');await has(section('harness').locator('.lab-log'),'自動で迂回しない');await click('harness','ツールが失敗');for(let i=0;i<5;i++)await click('harness','1ステップ →');await has(section('harness').locator('.lab-log'),'1回再試行');});
await check('20 controls change risk outcome',async()=>{await go('trust');await click('trust','許可のない送信');await click('trust','この構成で検証');await has(section('trust').locator('.lab-result'),'不足');await section('trust').getByLabel('最小権限・承認点').check();await click('trust','この構成で検証');await has(section('trust').locator('.lab-result'),'拒否');});
await check('21 adoption branches, backtracking and reset',async()=>{await go('adoption');for(const name of ['固定手順で解ける','データ境界が未整理','送信や更新を伴う','まだ定義していない'])await click('adoption',name);await has(section('adoption').locator('.lab-result'),'実データへの接続は保留');await click('adoption','← 一つ戻る');await click('adoption','合否と失敗例を定義済み');await has(section('adoption').locator('.lab-result'),'既存の基準');await click('adoption','↺ 最初から');await has(section('adoption').locator('.adoption-question'),'業務');});
await check('22 layer diagnosis repairs the actual artifact',async()=>{await go('synthesis');await click('synthesis','重複実行');await section('synthesis').locator('.system-shell').nth(0).click();assert.equal(await section('synthesis').locator('.system-terminal > button').isDisabled(),true);await section('synthesis').locator('.system-shell').nth(2).click();await click('synthesis','冪等キーを適用');await has(section('synthesis').locator('.terminal-diff'),'ALREADY_SAVED');await has(section('synthesis').locator('.system-terminal header'),'PASS');});
await check('23 sources are a compact ordered list',async()=>{await go('sources');assert.equal(await section('sources').locator('ol.source-list > li').count(),44);assert.equal(await section('sources').locator('.reference-grid,.source-filter').count(),0);assert.equal(await section('sources').locator('.source-list a').first().getAttribute('target'),'_blank');const rows=await section('sources').locator('.source-list li').evaluateAll(es=>es.slice(0,4).map(e=>({x:e.getBoundingClientRect().x,y:e.getBoundingClientRect().y})));assert.ok(rows.every(row=>row.x===rows[0].x));assert.ok(rows[1].y>rows[0].y);});
await check('20 choose action and return to prototyping',async()=>{await go('takeaway');await click('takeaway','小さく始める');await has(section('takeaway').locator('.slide-lab .takeaway-action'),'短い試作');await click('takeaway','試作の考え方へ ↗');await page.waitForFunction(()=>document.querySelector('#presentation').dataset.currentSlide==='vibe');});
await check('fullscreen, modal focus and navigation guard',async()=>{await go('manifesto');await page.getByRole('button',{name:'全画面表示',exact:true}).click();await page.waitForFunction(()=>Boolean(document.fullscreenElement));await section('manifesto').locator('.card-reveal-trigger').first().click();await page.keyboard.press('ArrowRight');assert.equal(await page.locator('#presentation').getAttribute('data-current-slide'),'manifesto');await page.keyboard.press('Escape');await page.waitForFunction(()=>!document.querySelector('dialog[open]'));await page.evaluate(()=>document.exitFullscreen());});
const ids=await page.locator('section[data-slide-id]:not([hidden])').evaluateAll(es=>es.sort((a,b)=>Number(a.style.order)-Number(b.style.order)).map(e=>e.dataset.slideId));
for (const [index,id] of ids.entries()) {
 await go(id);await page.waitForTimeout(600);
 layouts.push(await section(id).evaluate(e=>({id:e.dataset.slideId,width:e.clientWidth,scrollWidth:e.scrollWidth,height:e.clientHeight,scrollHeight:e.scrollHeight})));
 await page.screenshot({path:`outputs/direct-review/${String(index+1).padStart(2,'0')}-${id}.png`});
}
await check('all 20 desktop widths fit',async()=>{assert.equal(ids.length,20);assert.deepEqual(layouts.filter(x=>x.scrollWidth>x.width+2),[]);});
const mobile=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,reducedMotion:'reduce'});
await mobile.addInitScript(()=>localStorage.setItem('gen-ai-slide-settings-v2',JSON.stringify({hidden:[]})));
const touch=await mobile.newPage();touch.on('pageerror',e=>errors.push(e.message));
await touch.goto(base,{waitUntil:'networkidle',timeout:60000});
const mobileLayouts=[];
for(const id of ids) {
 await touch.evaluate(id=>{const s=document.querySelector(`section[data-slide-id="${id}"]`);document.querySelector('#presentation').scrollTop=s.offsetTop;},id);
 await touch.waitForFunction(id=>document.querySelector('#presentation').dataset.currentSlide===id,id);
 const target=touch.locator(`section[data-slide-id="${id}"]`);
 mobileLayouts.push(await target.evaluate(e=>({id:e.dataset.slideId,width:e.clientWidth,scrollWidth:e.scrollWidth,panels:[...e.querySelectorAll('.slide-lab,.direct-scene')].map(p=>({width:p.clientWidth,scroll:p.scrollWidth}))})));
 if(['cover','timeline','media','open-local','agent','mcp','concepts','commodity','engineering','synthesis','sources'].includes(id)) await touch.screenshot({path:`outputs/direct-review/mobile-${id}.png`});
 if(id==='mcp') await check('touch MCP uses click alternative',async()=>{await target.locator('.protocol-servers button').nth(2).tap();await pressed(target.locator('.protocol-servers button').nth(2));});
}
await check('all 20 mobile widths and panel widths fit',async()=>assert.deepEqual(mobileLayouts.filter(x=>x.scrollWidth>x.width+2||x.panels.some(p=>p.scroll>p.width+2)),[]));
await check('reduced motion retains keyboard and native cursor',async()=>{
 await touch.evaluate(()=>{const s=document.querySelector('[data-slide-id="reasoning"]');document.querySelector('#presentation').scrollTop=s.offsetTop;});await touch.waitForFunction(()=>document.querySelector('#presentation').dataset.currentSlide==='reasoning');
 await touch.locator('[data-slide-id="reasoning"]').getByRole('button',{name:'1ステップ →',exact:true}).tap();await has(touch.locator('[data-slide-id="reasoning"] .lab-result'),'32,000');
 assert.notEqual(await touch.locator('#presentation').evaluate(e=>getComputedStyle(e).cursor),'none');
});
await check('no instructional interaction banners',async()=>{assert.equal(await page.locator('.lab-heading').count(),0);assert.ok(!(await page.locator('#presentation').innerText()).includes('INTERACTIVE /'));});
await check('no application runtime errors',async()=>assert.deepEqual(errors,[]));
await writeFile('outputs/direct-review/report.json',JSON.stringify({results,errors,layouts,mobileLayouts},null,2));
await browser.close();
console.log(JSON.stringify({passed:results.filter(r=>r.pass).length,failed:results.filter(r=>!r.pass)},null,2));
if(results.some(r=>!r.pass))process.exitCode=1;
