import assert from 'node:assert/strict';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE || 'playwright');
import {writeFile,readFile,mkdir} from 'node:fs/promises';
await mkdir('output/playwright/studio-regression',{recursive:true});
const browser=await chromium.launch({headless:true,...(process.env.PLAYWRIGHT_CHANNEL?{channel:process.env.PLAYWRIGHT_CHANNEL}:{})}),p=await browser.newPage({viewport:{width:1440,height:1000},reducedMotion:'reduce'});
const results=[],errors=[],layouts=[];p.on('pageerror',e=>errors.push(e.message));
const base=process.env.STUDIO_URL||'http://127.0.0.1:5173/';
async function check(name,fn){try{await fn();results.push({name,pass:true});console.log('PASS',name);}catch(e){results.push({name,pass:false,error:e.message});console.log('FAIL',name,e.message.slice(0,500));}}
async function go(n,page=p){if(!(await page.locator('.studio-index').count()))await page.locator('.studio-index-toggle').click();await page.locator('.studio-index-chapter').nth(n).click();await page.waitForTimeout(130);}
await p.goto(base,{waitUntil:'networkidle'});await p.locator('.studio-scene[data-status=ready]').waitFor();
await check('starts in fullscreen 3D with no explanations, no sidebar, one canvas',async()=>{assert.equal(await p.locator('.studio-copy').count(),0);assert.equal(await p.locator('.studio-route').count(),0);assert.equal(await p.locator('canvas').count(),1);assert.equal(await p.locator('iframe').count(),0);const r=await p.locator('canvas').boundingBox();assert.equal(r.width,1440);assert.equal(r.height,1000);await p.screenshot({path:'output/playwright/studio-regression/final-room.png'});});
await check('8 chapters, 600 seconds, complete Japanese manuscript',async()=>{const t=await readFile('app/studio/content.ts','utf8');const scripts=[...t.matchAll(/script: "([^"]+)"/g)].map(m=>m[1]);assert.equal(scripts.length,8);assert.ok(scripts.join('').length>=2100&&scripts.join('').length<=2400);assert.equal([...t.matchAll(/time: (\d+)/g)].reduce((s,m)=>s+(+m[1]),0),600);});
await check('all seven objects open their own content and close to the room',async()=>{for(const [id,n] of [['name',0],['notebook',1],['board',3],['monitor',4],['cards',5],['checklist',6],['library',2]]){await go(2);await p.locator(`[data-object=${id}]`).click();if(id==='library'){assert.ok(await p.locator('.studio-library-dialog').isVisible());await p.getByRole('button',{name:'資料を閉じて元の章に戻る'}).click();}else{assert.equal(await p.locator('.work-studio').getAttribute('data-chapter'),String(n));assert.ok(await p.locator('.studio-copy').isVisible());await p.getByRole('button',{name:'閉じて全景に戻る'}).click();assert.equal(await p.locator('.studio-copy').count(),0);}}});
await check('actual monitor mesh is clickable, not just hotspot buttons',async()=>{
 await go(2);
 const a=await p.locator('[data-object=monitor]').evaluate(e=>({x:Number(e.dataset.anchorX),y:Number(e.dataset.anchorY)}));
 // The wider garden view puts the monitor under its accessible 44px hotspot.
 // Disable only HTML hit-testing to independently exercise the physical mesh.
 await p.locator('.studio-object').evaluateAll(items=>items.forEach(e=>e.style.pointerEvents='none'));
 try {
  await p.mouse.move(a.x+6,a.y+14);await p.waitForTimeout(80);
  assert.equal(await p.locator('[data-object=monitor]').getAttribute('data-hovered'),'true');
  await p.mouse.click(a.x+6,a.y+14);await p.locator('.studio-scene[data-view=monitor]').waitFor();
  assert.equal(await p.locator('.work-studio').getAttribute('data-chapter'),'4');
 }finally{await p.locator('.studio-object').evaluateAll(items=>items.forEach(e=>e.style.removeProperty('pointer-events')));}
});
await check('Agent failure and repair visibly change real 320px HTML',async()=>{await go(4);await p.getByRole('button',{name:'4 問題を見つける',exact:true}).click();const before=await p.locator('.studio-mini-viewport').evaluate(e=>({w:e.clientWidth,button:e.querySelector('.studio-example-button').getBoundingClientRect().width,overflow:e.scrollWidth>e.clientWidth}));assert.equal(before.button,380);assert.ok(before.overflow);await p.screenshot({path:'output/playwright/studio-regression/agent-failure.png'});await p.getByRole('button',{name:'6 同じ条件で確かめる',exact:true}).click();const after=await p.locator('.studio-mini-viewport').evaluate(e=>({w:e.clientWidth,button:e.querySelector('.studio-example-button').getBoundingClientRect().width,overflow:e.scrollWidth>e.clientWidth}));assert.equal(after.w,before.w);assert.equal(after.button,284);assert.equal(after.overflow,false);await p.screenshot({path:'output/playwright/studio-regression/agent-fixed.png'});await p.getByRole('button',{name:'Agentデモをリセット'}).click();assert.ok((await p.locator('.studio-step-text').innerText()).includes('完了の条件'));});
await check('Agent replay pauses, advances, and stops at delivery',async()=>{await p.getByRole('button',{name:'再生',exact:true}).click();await p.waitForTimeout(2500);await p.getByRole('button',{name:'一時停止',exact:true}).click();assert.equal(await p.locator('.studio-step-track [aria-current=step] span').innerText(),'2');await p.getByRole('button',{name:'7 結果と確認範囲を渡す',exact:true}).click();assert.ok(await p.getByRole('button',{name:'再生',exact:true}).isDisabled());});
await check('Day Card theme, draw, reveal, repeat and process notes work',async()=>{await go(5);await p.getByRole('button',{name:'新しく始める',exact:true}).click();await p.getByRole('button',{name:'一枚、ひいてみる'}).click();await p.getByRole('button',{name:'カードを裏返す',exact:true}).click();assert.ok((await p.locator('.studio-card-front').innerText()).includes('小さな一歩'));await p.screenshot({path:'output/playwright/studio-regression/daycard-result.png'});await p.getByRole('button',{name:'もう一度ひく'}).click();assert.equal(await p.locator('.studio-play-card').getAttribute('data-drawn'),'false');for(const name of ['Idea','Design','Build','Try','Improve']){await p.getByRole('button',{name,exact:true}).click();assert.ok((await p.locator('.studio-process-text').innerText()).length>10);}});
await check('human review changes preview and scene checks',async()=>{await go(6);for(const box of await p.locator('.studio-checklist input').all())await box.check();assert.equal(await p.locator('.studio-review-preview').getAttribute('data-clear'),'true');assert.ok((await p.locator('.studio-review-preview').innerText()).includes('人のレビューへ'));});
await check('archive searches all 24 old pages, deep links, unmounts and restores state',async()=>{await go(4);await p.getByRole('button',{name:'4 問題を見つける',exact:true}).click();await p.getByRole('button',{name:'参考資料',exact:true}).click();assert.equal(await p.locator('.studio-library-grid>button').count(),24);await p.getByRole('searchbox',{name:'資料を検索'}).fill('Evals');await p.locator('.studio-library-grid>button').click();await p.frameLocator('iframe').locator('#presentation[data-current-slide=trust]').waitFor({timeout:60000});await p.getByRole('button',{name:'資料を閉じて元の章に戻る'}).click();assert.equal(await p.locator('iframe').count(),0);assert.ok((await p.locator('.studio-step-text').innerText()).includes('問題を見つける'));});
await check('index mode switch preserves interaction state',async()=>{await go(5);await p.getByRole('button',{name:'一枚、ひいてみる'}).click();await p.locator('.studio-index-toggle').click();await p.getByRole('button',{name:'自由探索',exact:true}).click();assert.equal(await p.locator('.work-studio').getAttribute('data-mode'),'explore');assert.equal(await p.locator('.studio-play-card').getAttribute('data-drawn'),'true');await p.getByRole('button',{name:'10分ガイド',exact:true}).click();await p.getByRole('button',{name:'目次を閉じる',exact:true}).click();});
await check('keyboard navigation, Escape and Enter',async()=>{await go(3);await p.keyboard.press('ArrowRight');assert.equal(await p.locator('.work-studio').getAttribute('data-chapter'),'4');await p.keyboard.press('ArrowLeft');assert.equal(await p.locator('.work-studio').getAttribute('data-chapter'),'3');await p.keyboard.press('Escape');assert.equal(await p.locator('.studio-copy').count(),0);await p.keyboard.press('Enter');assert.equal(await p.locator('.studio-scene').getAttribute('data-view'),'board');});
await check('speaker timer is optional and never changes chapters automatically',async()=>{await p.locator('.studio-index-toggle').click();await p.getByRole('button',{name:'講者モードを開く'}).click();assert.ok((await p.locator('.studio-script').innerText()).length>150);await p.getByRole('button',{name:'計時を開始'}).click();await p.waitForTimeout(1150);assert.notEqual(await p.locator('.studio-notes-clock>b').innerText(),'0:00');await p.getByRole('button',{name:'計時を停止'}).click();await p.locator('.studio-notes-dialog').getByRole('button',{name:'閉じる ×'}).click();assert.equal(await p.locator('.work-studio').getAttribute('data-chapter'),'3');});
await check('idle scene stops rendering',async()=>{await go(2);await p.mouse.move(0,0);await p.waitForTimeout(500);const frames=await p.locator('.studio-scene').getAttribute('data-frames');await p.waitForTimeout(500);assert.equal(await p.locator('.studio-scene').getAttribute('data-frames'),frames);});
for(const [width,height] of [[1366,768],[820,1180],[390,844],[320,720]]){
 await p.setViewportSize({width,height});await check(`all interaction surfaces fit ${width}×${height}`,async()=>{for(let n=0;n<8;n++){await go(n);const m=await p.evaluate(()=>{const el=document.querySelector('.studio-copy'),f=document.querySelector('.studio-footer').getBoundingClientRect();return {body:document.documentElement.scrollWidth,w:innerWidth,panelOverflow:el?el.scrollWidth>el.clientWidth+2:false,panelBottom:el?.getBoundingClientRect().bottom||0,footerTop:f.top,canvasHeight:document.querySelector('canvas').getBoundingClientRect().height};});layouts.push({width,height,chapter:n,...m});assert.ok(m.body<=width+1,JSON.stringify(m));assert.equal(m.panelOverflow,false,JSON.stringify(m));assert.ok(m.panelBottom<=m.footerTop,JSON.stringify(m));assert.equal(m.canvasHeight,height);if([2,4,5].includes(n))await p.screenshot({path:`output/playwright/studio-regression/${width}-chapter-${n+1}.png`});}});
}
await check('touch drawing and flipping work with reduced motion',async()=>{const ctx=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,reducedMotion:'reduce'}),q=await ctx.newPage();await q.goto(base);await q.locator('.studio-scene[data-status=ready]').waitFor();await go(5,q);await q.getByRole('button',{name:'一枚、ひいてみる'}).tap();await q.getByRole('button',{name:'カードを裏返す',exact:true}).tap();assert.ok(await q.locator('.studio-play-card').evaluate(e=>e.classList.contains('is-flipped')));await q.screenshot({path:'output/playwright/studio-regression/mobile-touch-result.png'});await ctx.close();});
await check('WebGL unavailable exposes same interactions and retry',async()=>{const q=await browser.newPage();await q.goto(base+'?no3d=1');await q.locator('.studio-fallback').waitFor();assert.equal(await q.locator('canvas').count(),0);await go(4,q);assert.ok(await q.getByRole('button',{name:'次のステップ →',exact:true}).isVisible());await q.getByRole('button',{name:'3Dを再読み込み',exact:true}).click();await q.locator('.studio-scene[data-status=ready]').waitFor();await q.close();});
await p.setViewportSize({width:1440,height:1000});await p.emulateMedia({reducedMotion:'no-preference'});
await check('rapid navigation replaces camera transition; dragging does not activate objects',async()=>{await go(2);await p.locator('.studio-index-toggle').click();await p.locator('.studio-index').evaluate(el=>{const b=el.querySelectorAll('.studio-index-chapter');[0,5,1,3,6,4,2].forEach(i=>b[i].click());});await p.waitForTimeout(2800);assert.equal(await p.locator('.studio-scene').getAttribute('data-view'),'room');assert.equal(await p.locator('.studio-scene').getAttribute('data-transition'),'false');await p.mouse.move(700,620);await p.mouse.down();await p.mouse.move(760,640,{steps:8});await p.mouse.up();assert.equal(await p.locator('.studio-copy').count(),0);});
await check('context loss offers working recovery',async()=>{await p.locator('canvas').evaluate(c=>c.getContext('webgl2').getExtension('WEBGL_lose_context').loseContext());await p.locator('.studio-fallback').waitFor();await p.getByRole('button',{name:'3Dを再読み込み',exact:true}).click();await p.locator('.studio-scene[data-status=ready]').waitFor();assert.equal(await p.locator('canvas').count(),1);});
await check('no runtime exceptions',async()=>assert.deepEqual(errors,[]));
await writeFile('output/playwright/studio-regression/test-results.json',JSON.stringify({results,errors,layouts},null,2));console.log(`${results.filter(r=>r.pass).length}/${results.length} passed`);await browser.close();if(results.some(r=>!r.pass))process.exitCode=1;

