import assert from 'node:assert/strict';
import {chromium} from 'file:///C:/Users/70893804/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs';
import {writeFile,readFile} from 'node:fs/promises';
import {execFileSync} from 'node:child_process';
import {createHash} from 'node:crypto';
async function go(page,n){await page.locator('.studio-index-toggle').click();await page.locator('.studio-index-chapter').nth(n).click();} const results=[];async function check(name,fn){try{await fn();results.push({name,pass:true});console.log('PASS',name);}catch(e){results.push({name,pass:false,error:e.message});console.log('FAIL',name,e.message.slice(0,350));}}
await check('archive original page hash equals pre-change backup bytes',async()=>{const bytes=execFileSync('tar',['-xOf','C:/Users/70893804/Downloads/Codex/PJ-backup-20260928-studio/project-before-studio.tar','./app/page.tsx'],{maxBuffer:4e6});const hashes=JSON.parse(await readFile('outputs/studio-review/archive-hashes.json','utf8'));assert.equal(createHash('sha256').update(bytes).digest('hex'),hashes['app/LegacyDeck.tsx']);});
const browser=await chromium.launch({headless:true,channel:'msedge'});const p=await browser.newPage({viewport:{width:1440,height:1000},reducedMotion:'reduce'});await p.goto('http://localhost:5173/');await p.locator('.work-studio[data-ready=true]').waitFor({state:'attached'});
await check('profile edit saves in legacy and refreshes the main identity on return',async()=>{await go(p,0);await p.getByRole('button',{name:'参考資料',exact:true}).click();await p.locator('.studio-library-grid').getByRole('button').filter({hasText:'自己紹介'}).click();const frame=p.frameLocator('.studio-legacy-frame');await frame.locator('#presentation[data-ready=true]').waitFor();await frame.getByRole('button',{name:'編集',exact:true}).click();await frame.getByRole('textbox',{name:'氏名',exact:true}).fill('王 博 TEST');await frame.getByRole('button',{name:'保存',exact:true}).click();await p.getByRole('button',{name:'資料を閉じて元の章に戻る'}).click();assert.ok((await p.locator('.studio-profile h2').innerText()).includes('TEST'));});
await check('legacy hide and reorder controls persist their settings',async()=>{const old=await browser.newPage();await old.goto('http://localhost:5173/reference/');await old.locator('#presentation[data-ready=true]').waitFor();await old.getByRole('button',{name:'ページ編集',exact:true}).click();await old.getByRole('button',{name:'Reasoningを非表示にする',exact:true}).click();await old.getByRole('button',{name:'自己紹介を下へ移動',exact:true}).click();const saved=await old.evaluate(()=>JSON.parse(localStorage.getItem('gen-ai-slide-settings-v2')));assert.ok(saved.hidden.includes('reasoning'));assert.notEqual(saved.order[0],'intro');await old.close();});
await check('typing arrows in search does not navigate the presentation',async()=>{await go(p,3);await p.getByRole('button',{name:'参考資料',exact:true}).click();const search=p.getByRole('searchbox');await search.fill('MCP');await search.press('ArrowRight');assert.equal(await p.locator('.work-studio').getAttribute('data-chapter'),'3');await p.keyboard.press('Escape');await p.locator('.studio-library-dialog').waitFor({state:'hidden'});});
await check('3D module download failure leaves text usable and retry succeeds',async()=>{const ctx=await browser.newContext();const broken=await ctx.newPage();await broken.route('**/StudioCanvas-*.js',r=>r.abort());await broken.goto('http://127.0.0.1:5180/');await broken.getByText('3Dの読み込みに失敗しました。全章と参考資料は、引き続きご覧いただけます。',{exact:true}).waitFor({timeout:1000}).catch(()=>{});await broken.locator('.studio-fallback').waitFor();await go(broken,4);assert.ok(await broken.getByRole('button',{name:'次のステップ →',exact:true}).isVisible());await broken.unroute('**/StudioCanvas-*.js');await broken.getByRole('button',{name:'再読み込み',exact:true}).click();await broken.locator('.studio-scene[data-status=ready]').waitFor();await ctx.close();});
await browser.close();await writeFile('outputs/redesign/edgecase-results.json',JSON.stringify(results,null,2));if(results.some(r=>!r.pass))process.exitCode=1;


