import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
import {mockWeather} from './weather-fixture.mjs';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'playwright');
const out='output/playwright/interactions';await mkdir(out,{recursive:true});
const browser=await chromium.launch({headless:true,...(process.env.PLAYWRIGHT_CHANNEL?{channel:process.env.PLAYWRIGHT_CHANNEL}:{})});
const page=await browser.newPage({viewport:{width:1440,height:1000},reducedMotion:'no-preference'});page.setDefaultTimeout(15000);
const errors=[],reports=[];page.on('pageerror',e=>errors.push(e.message));
const scene=page.locator('.studio-scene');
const state=async()=>JSON.parse(await scene.getAttribute('data-props'));
const settled=()=>page.waitForFunction(()=>document.querySelector('.studio-scene')?.dataset.transition==='false');
const inspect=async(id)=>{await page.locator(`[data-prop="${id}"]`).click();await page.waitForFunction(id=>document.querySelector('.studio-scene')?.dataset.inspection===id,id);await settled();};
const back=async()=>{await page.mouse.click(24,180);await page.waitForFunction(()=>document.querySelector('.studio-scene')?.dataset.inspection==='');await settled();};
const shot=async(name)=>page.screenshot({path:`${out}/${name}.png`});
const pass=name=>{reports.push({name,pass:true});console.log('PASS',name);};
try{
 await mockWeather(page);await page.goto(process.env.STUDIO_URL||'http://127.0.0.1:5180/',{waitUntil:'networkidle'});await page.locator('.studio-scene[data-status="ready"]').waitFor();await settled();
 assert.equal(await scene.getAttribute('data-music'),'paused');assert.equal(await page.locator('.studio-prop[data-prop]').count(),15);assert.equal(await page.locator('.studio-object').count(),4);assert.equal(await page.locator('.prop-controls,.music-pause').count(),0);await shot('overview');pass('immersive room has no persistent prop labels and no autoplay');
 const initial=await scene.getAttribute('data-camera-position');await inspect('desk-lamp');assert.equal((await state()).deskLamp,false);assert.equal((await state()).lampIntensity[0],0);assert.notEqual(await scene.getAttribute('data-camera-position'),initial);await page.locator('[data-prop=desk-lamp]').click();await page.waitForFunction(()=>JSON.parse(document.querySelector('.studio-scene').dataset.props).lampIntensity[0]>0);await shot('desk-light');await back();pass('desk lamp switches off and on, camera focuses then returns');
 await inspect('floor-lamp');assert.equal((await state()).floorLamp,false);assert.equal((await state()).lampIntensity[1],0);await page.locator('[data-prop=floor-lamp]').click();await back();pass('floor lamp controls its own bulb and local illumination');
 for(const [id,index] of [['rear-curtain',1],['left-curtain',0]]){await inspect(id);await page.waitForFunction(i=>JSON.parse(document.querySelector('.studio-scene').dataset.props).curtains[i].open<.005,index);await shot(id+'-closed');await page.locator(`[data-prop="${id}"]`).click();await page.waitForFunction(i=>JSON.parse(document.querySelector('.studio-scene').dataset.props).curtains[i].open>.995,index);await shot(id+'-open');await back();}pass('both linen curtains gather and close independently');
 await inspect('chalkboard');const canvas=page.locator('.chalk-writing-canvas');await canvas.waitFor({state:'visible'});assert.match(await canvas.evaluate(e=>getComputedStyle(e).cursor),/image\/svg/);const before=await canvas.evaluate(c=>c.toDataURL());const r=await canvas.boundingBox();await page.mouse.move(r.x+r.width*.76,r.y+r.height*.8);await page.mouse.down();await page.mouse.move(r.x+r.width*.88,r.y+r.height*.84,{steps:12});await page.mouse.up();const drawn=await canvas.evaluate(c=>c.toDataURL());assert.notEqual(drawn,before);await shot('chalk-written');await page.mouse.click(r.x+r.width*.876,r.y+r.height*1.045);assert.equal(await page.getByRole('button',{name:'黒板消し',exact:true}).getAttribute('aria-pressed'),'true');assert.notEqual(await canvas.evaluate(e=>getComputedStyle(e).cursor),'cell');await page.mouse.move(r.x+r.width*.76,r.y+r.height*.8);await page.mouse.down();await page.mouse.move(r.x+r.width*.88,r.y+r.height*.84,{steps:12});await page.mouse.up();assert.notEqual(await canvas.evaluate(c=>c.toDataURL()),drawn);await shot('chalk-erased');await page.mouse.click(r.x+r.width*.27,r.y+r.height*1.055);await page.waitForFunction(()=>document.querySelector('[data-chalk-tool=chalk]').getAttribute('aria-pressed')==='true');assert.equal(await page.getByRole('button',{name:'粉筆',exact:true}).getAttribute('aria-pressed'),'true');await back();await inspect('chalkboard');assert.equal((await state()).ink,'2');await back();pass('chalk draws on physical board; eraser removes strokes and ink survives focus changes');
 await inspect('gramophone');await page.waitForFunction(()=>document.querySelector('.studio-scene').dataset.music==='playing');await shot('gramophone');await page.locator('[data-prop=gramophone]').focus();const oldVolume=Number(await scene.getAttribute('data-volume'));await page.keyboard.press('ArrowUp');assert.ok(Number(await scene.getAttribute('data-volume'))>oldVolume);await page.locator('[data-prop=gramophone]').click();await page.waitForFunction(()=>document.querySelector('.studio-scene').dataset.music==='paused');await back();pass('gramophone starts original BGM only on click, supports volume and pause');
 for(const id of ['sofa','chair','plant','coffee','cabinet','robot','clock']){await inspect(id);await shot(id);if(id==='robot'){assert.equal((await state()).robotPaused,true);const stopped=JSON.parse(await scene.getAttribute('data-life')).time;await page.locator('[data-prop=robot]').click();await page.waitForFunction(t=>JSON.parse(document.querySelector('.studio-scene').dataset.life).time>t+.25,stopped);}if(id==='coffee')assert.equal(JSON.parse(await scene.getAttribute('data-life')).steam.visible,true);await back();}pass('living props focus and respond without blocking the chapter entrances');
 await inspect('cabinet');assert.deepEqual((await state()).doorsOpen,[false,false,false,false]);for(let i=0;i<4;i++){await page.locator(`[data-door="${i}"]`).click();await page.waitForFunction(i=>JSON.parse(document.querySelector('.studio-scene').dataset.props).doorsOpen[i],i);}await page.waitForTimeout(1100);await shot('four-doors-open');for(let i=0;i<4;i++)await page.locator(`[data-door="${i}"]`).click();await back();pass('four narrow cabinet doors open and close independently at their handles');
 await inspect('desk-drawer');assert.equal((await state()).drawerOpen,true);await shot('desk-drawer-open');await page.locator('[data-prop=desk-drawer]').click();await page.waitForFunction(()=>!JSON.parse(document.querySelector('.studio-scene').dataset.props).drawerOpen);assert.equal((await state()).drawerOpen,false);await back();await inspect('hourglass');const timer=await state();assert.equal(timer.timerFlips,1);await shot('hourglass');await page.waitForFunction(t=>JSON.parse(document.querySelector('.studio-scene').dataset.props).timerRemaining<t,timer.timerRemaining-.3);await page.locator('[data-prop=hourglass]').click();await page.waitForFunction(()=>JSON.parse(document.querySelector('.studio-scene').dataset.props).timerFlips===2);assert.equal((await state()).timerFlips,2);await back();pass('desk drawer reveals stationery and the hourglass reverses and runs');
 await page.locator('.garden-start').click();await page.locator('[data-kind=name][data-interactive=true]').waitFor();assert.equal(await page.getByText('画像処理・機械学習エンジニア',{exact:true}).count(),0);await shot('intro');const bookCamera=await scene.getAttribute('data-camera-position');await page.locator('.journey-dots button').nth(1).click();await page.waitForFunction(()=>document.querySelector('.studio-scene').dataset.pageTransition==='paper');await page.waitForTimeout(280);await shot('page-turn');const turn=await page.locator('.book-turn-sheet').evaluate(e=>({x:Number(e.dataset.tipX),z:Number(e.dataset.tipDepth),width:e.clientWidth}));assert.ok(turn.z>0,'right edge lifts toward the reader');assert.ok(turn.x<turn.width,'page travels left from its fixed spine');assert.equal(await page.locator('.book-turn-strip').count(),20);assert.equal(await page.locator('.book-turn-sheet [id]').count(),0);await page.locator('[data-kind=notebook][data-interactive=true]').waitFor();assert.equal(await scene.getAttribute('data-camera-position'),bookCamera);pass('journal turns a sheet without camera detour and introduction uses personal work wording');
 await page.locator('.journey-dots button').nth(2).click();await page.locator('[data-kind=board][data-interactive=true]').waitFor();await shot('llm-monitor');const monitorColor=await page.locator('.model-board').evaluate(e=>getComputedStyle(e).backgroundColor);const monitorCamera=await scene.getAttribute('data-camera-position');await page.locator('.journey-dots button').nth(3).click();await page.waitForFunction(()=>document.querySelector('.studio-scene').dataset.pageTransition==='screen');await page.locator('[data-kind=monitor][data-interactive=true]').waitFor();assert.equal(await scene.getAttribute('data-camera-position'),monitorCamera);assert.equal(await page.locator('.model-monitor').evaluate(e=>getComputedStyle(e).backgroundColor),monitorColor);await shot('agent-monitor');pass('LLM and Agent have one monitor style and a stationary screen transition');
 await page.locator('.journey-dots button').nth(4).click();await page.locator('[data-kind=checklist][data-interactive=true]').waitFor();await page.getByRole('tab',{name:'競争力',exact:true}).click();assert.equal(await page.getByText('議論の論点',{exact:true}).count(),0);assert.match(await page.locator('.advantage-closing').innerText(),/専門性をどの業務に活かし/);await shot('discussion');pass('closing discussion uses concise presentation wording');
 for(const [width,height] of [[1920,1080],[1440,900],[1280,720],[1280,600],[1024,576],[960,540]]){
  await page.setViewportSize({width,height});await settled();
  const bounds=await page.locator('.model-checklist .model-page-scroll').evaluate(e=>{const r=e.getBoundingClientRect();return {h:e.clientHeight,scroll:e.scrollHeight,w:e.clientWidth,scrollW:e.scrollWidth,bad:[...e.querySelectorAll('p,h1,h2,small,button')].filter(c=>{const b=c.getBoundingClientRect();return b.bottom>r.bottom+1||b.right>r.right+1||b.left<r.left-1;}).map(c=>c.textContent),scale:e.getBoundingClientRect().width/e.offsetWidth};});
  assert.ok(bounds.scroll<=bounds.h+1&&bounds.scrollW<=bounds.w+1,JSON.stringify({width,height,...bounds}));assert.deepEqual(bounds.bad,[],JSON.stringify({width,height,...bounds}));assert.ok(Math.abs(bounds.scale-1)<.01,'text retains its natural proportions');
  await shot(`value-${width}-${height}`);
 }await page.setViewportSize({width:1440,height:1000});pass('discussion fits six PC window sizes without scrolling, clipping or stretched text');
 await page.reload({waitUntil:'networkidle'});await page.locator('.studio-scene[data-status=ready]').waitFor();assert.equal((await state()).ink,'0');assert.equal(await scene.getAttribute('data-music'),'paused');await inspect('chalkboard');assert.equal(await canvas.evaluate(c=>c.toDataURL()),before);pass('reload restores original chalk sketch and leaves music off');
 assert.deepEqual(errors,[]);pass('no uncaught browser errors');
}catch(error){await shot('failure');console.error(await scene.getAttribute('data-props'));throw error;}finally{await writeFile(out+'/report.json',JSON.stringify({reports,errors},null,2));await browser.close();}
