export type AtlasMode = "evolution" | "architecture";
export type AtlasNode = {
  id: string; label: string; title: string; category: string; date: string;
  color: string; position: [number, number, number]; summary: string;
  facts: [string, string][]; flow: string[]; boundary: string;
  sources: string[]; related: string[]; slide: string;
};

export const atlasSources: Record<string, { title: string; url: string }> = {
  transformer: { title: "Vaswani et al. · Attention Is All You Need · 2017", url: "https://arxiv.org/abs/1706.03762" },
  rag: { title: "Lewis et al. · Retrieval-Augmented Generation · 2020", url: "https://arxiv.org/abs/2005.11401" },
  react: { title: "Yao et al. · ReAct · 2022", url: "https://arxiv.org/abs/2210.03629" },
  functions: { title: "OpenAI · Function calling and other API updates · 2023", url: "https://openai.com/index/function-calling-and-other-api-updates/" },
  computer: { title: "Anthropic · Developing a computer use model · 2024", url: "https://www.anthropic.com/news/developing-computer-use" },
  mcp: { title: "Anthropic · Introducing the Model Context Protocol · 2024", url: "https://www.anthropic.com/news/model-context-protocol" },
  protocol: { title: "Model Context Protocol · Architecture overview", url: "https://modelcontextprotocol.io/docs/learn/architecture" },
  agents: { title: "Anthropic · Building effective agents · 2024", url: "https://www.anthropic.com/engineering/building-effective-agents" },
  codex: { title: "OpenAI · Introducing Codex · 2025", url: "https://openai.com/index/introducing-codex/" },
  long: { title: "Anthropic · Effective harnesses for long-running agents · 2025", url: "https://www.anthropic.com/engineering/effective-harnesses-for-long-running-agents" },
  harness: { title: "OpenAI · Harness engineering · 2026", url: "https://openai.com/index/harness-engineering/" },
};

const blue = "#78b8ff", teal = "#64e2ca", gold = "#e8c78f";
export const evolutionNodes: AtlasNode[] = [
  { id: "transformer", label: "Transformer", title: "言語モデルの基盤", category: "論文", date: "2017.06", color: blue, position: [-8, -.5, 1], summary: "注意機構を中心とするモデル構造が、その後の大規模言語モデルの基盤になった。", facts: [["構造", "再帰や畳み込みに依存せず、注意機構で系列の関係を扱う。"], ["Agentとの関係", "現在のLLM型Agentを支えるモデル技術の一つ。単体で行動するAgentではない。"]], flow: ["入力", "Attention", "表現", "出力"], boundary: "この年表は現代のLLM型Agentにつながる主要な節目を扱う。Agent研究全体の始まりを2017年とするものではない。", sources: ["transformer"], related: ["model", "retrieval"], slide: "timeline" },
  { id: "retrieval", label: "RAG", title: "検索を、生成の根拠へ", category: "論文", date: "2020.05", color: blue, position: [-6, 1, -1.6], summary: "モデルのパラメータ内の知識と、外部から検索した情報を組み合わせて文章を生成する。", facts: [["発表", "LewisらのRAG論文は2020年5月22日に公開。2023年は誕生年ではない。"], ["役割", "必要な文書を取得し、生成時の文脈に加える。業務固有の知識を参照する設計につながる。"]], flow: ["質問", "検索", "文脈", "回答"], boundary: "RAGだけでAgentになるわけではなく、検索結果が正しいことも自動では保証されない。", sources: ["rag"], related: ["context", "react-loop"], slide: "concepts" },
  { id: "react-loop", label: "ReAct", title: "判断と行動を往復する", category: "論文", date: "2022.10", color: teal, position: [-4, -.15, 1.4], summary: "外部への行動と、その結果を踏まえた次の判断を交互に進める構成を示した。", facts: [["発表", "2022年10月6日に論文公開、ICLR 2023で発表。"], ["変化", "質問への一度の回答から、検索や操作の結果を受け取って進め方を更新する流れへ。"]], flow: ["判断", "行動", "観察", "次の判断"], boundary: "図は制御の循環を表す。モデル内部の思考をそのまま表示・検証できるという意味ではない。", sources: ["react"], related: ["loop", "function-calling"], slide: "agent" },
  { id: "function-calling", label: "Tool use", title: "自然言語からツール呼び出しへ", category: "API公開", date: "2023.06", color: teal, position: [-2, 1.3, -1.5], summary: "OpenAIは2023年6月13日、関数名と構造化した引数を返すFunction CallingをAPIに導入した。", facts: [["モデル", "利用する関数と引数を生成する。"], ["アプリ", "引数と権限を検証し、実際の関数を実行して結果をモデルへ戻す。"]], flow: ["要求", "引数", "アプリが実行", "結果"], boundary: "モデルがAPIを直接実行するわけではない。ツール利用の研究自体はこの公開以前から存在する。", sources: ["functions"], related: ["tools", "protocol", "computer-use"], slide: "concepts" },
  { id: "computer-use", label: "Computer use", title: "画面を介して操作する", category: "公開ベータ", date: "2024.10", color: teal, position: [0, -.3, 1.4], summary: "Anthropicは2024年10月22日、画面を読み取り、クリックや入力を行うcomputer useを公開した。", facts: [["入力", "スクリーンショットから画面の状態と操作対象を捉える。"], ["実行", "操作ツールで入力し、変化した画面を再び観察する。"]], flow: ["画面", "操作", "新しい画面", "確認"], boundary: "専用API以外の操作経路が広がった節目。誤操作や不確実性があり、重要操作の確認は必要。", sources: ["computer"], related: ["tools", "oversight", "mcp-release"], slide: "agent" },
  { id: "mcp-release", label: "MCP", title: "接続方法を共通化する", category: "プロトコル公開", date: "2024.11", color: teal, position: [2, 1.1, -1.5], summary: "2024年11月25日、AnthropicがModel Context Protocolを公開。AIアプリと外部のデータ・ツールを共通の方法で接続する。", facts: [["構造", "HostがClientを管理し、各ClientがServerと接続する。"], ["役割", "Tools・Resources・Promptsなどを、共通のプロトコルで提供する。"]], flow: ["Host", "Client", "Server", "データ・ツール"], boundary: "MCPはモデルでもAgentそのものでもない。すべてのAgentに必須の部品でもない。", sources: ["mcp", "protocol"], related: ["protocol", "coding-agent"], slide: "mcp" },
  { id: "coding-agent", label: "Coding agent", title: "補完から、タスク単位の開発へ", category: "製品公開例", date: "2025.05", color: gold, position: [4, -.1, 1.3], summary: "2025年5月16日に公開されたCodexの例では、リポジトリを読み、変更し、テストして成果物を返す単位へ作業が広がった。", facts: [["入力", "数行の補完だけでなく、機能や不具合の修正を依頼する。"], ["成果物", "差分と実行・検証の結果を、人がレビューできる形で返す。"]], flow: ["タスク", "編集", "テスト", "レビュー"], boundary: "Codexは製品化の一例であり、Coding Agentの最初の発明や全製品の共通公開日を示すものではない。", sources: ["codex"], related: ["harness", "long-running"], slide: "vibe" },
  { id: "long-running", label: "Long-running", title: "セッションを越えて継続する", category: "工程設計", date: "2025.11", color: gold, position: [6, 1.4, -1.4], summary: "Anthropicが2025年11月26日に示した実践では、初期化、進捗の記録、段階的な実装と検証を組み合わせる。", facts: [["問題", "コンテキストが切り替わると、途中の作業状態が失われやすい。"], ["設計", "進捗ファイル、Git履歴、テストと小さな実装単位で、次のセッションへ仕事を引き継ぐ。"]], flow: ["初期化", "実装", "検証・記録", "再開"], boundary: "長いコンテキストだけで継続性が解決するわけではない。外部に残す状態の設計が要る。", sources: ["long"], related: ["memory", "harness-practice"], slide: "harness" },
  { id: "harness-practice", label: "Harness", title: "Agentが働く環境を設計する", category: "工程実践", date: "2026.02", color: gold, position: [8, .1, 1.2], summary: "OpenAIの2026年2月11日の実践報告は、仕様、実行環境、テスト、可観測性などの設計に焦点を当てる。", facts: [["対象", "モデルを囲むツール、知識、制約、検証手段と開発環境。"], ["人の仕事", "完了条件を定義し、観察できる結果から環境とフィードバックを改善する。"]], flow: ["仕様", "環境", "実行", "評価・改善"], boundary: "この日付は記事の公開日。Harnessという考え方の誕生年や、統一された標準仕様の成立日ではない。", sources: ["harness", "long"], related: ["harness", "evaluation", "loop"], slide: "engineering" },
];

export const architectureNodes: AtlasNode[] = [
  { id: "model", label: "LLM", title: "生成・判断を担うモデル", category: "MODEL", date: "01", color: teal, position: [0, .8, 0], summary: "与えられた指示と文脈をもとに、応答や次のツール呼び出しを生成する中心要素。", facts: [["入力", "目的、指示、関連情報、直前の実行結果。"], ["出力", "応答、構造化データ、次の操作候補。実際の操作は実行環境が担う。"]], flow: ["文脈", "モデル", "応答・引数"], boundary: "モデル単体とAgentシステムは同じではない。モデルの出力には検証が必要。", sources: ["agents", "functions"], related: ["transformer", "context", "loop"], slide: "synthesis" },
  { id: "goal", label: "Goal / Prompt", title: "目的と完了条件", category: "CONTEXT", date: "02", color: blue, position: [-5, 1.3, 0], summary: "何を達成し、どの条件で完了と判断するかを、指示として渡す。", facts: [["目的", "例：出張申請の下書きを作る。送信は人が判断する。"], ["制約", "利用可能な情報・ツール、予算、停止条件を明確にする。"]], flow: ["目的", "制約", "完了条件"], boundary: "曖昧な指示や矛盾した条件は、実行環境だけでは解消できない。", sources: ["agents", "harness"], related: ["model", "oversight"], slide: "engineering" },
  { id: "context", label: "Context / RAG", title: "今回の判断に必要な情報", category: "CONTEXT", date: "03", color: blue, position: [-3, -.3, 3.5], summary: "履歴、文書、検索結果などを選び、モデルが参照できる文脈へ組み込む。", facts: [["RAG", "必要な文書を検索して生成へ渡す、一つの構成方法。"], ["選別", "多く入れるだけでなく、関連性、鮮度、出典を管理する。"]], flow: ["問い", "検索", "文脈", "モデル"], boundary: "RAGと記憶は役割が重なる場合があるが同義ではない。取得した文書は実行命令とは区別する。", sources: ["rag", "functions"], related: ["retrieval", "memory", "model"], slide: "concepts" },
  { id: "memory", label: "Memory / State", title: "次へ引き継ぐ状態", category: "CONTEXT", date: "04", color: blue, position: [-3, -.3, -3.5], summary: "途中結果、履歴、進捗などを外部に保存し、必要に応じて次の実行へ渡す。", facts: [["短い循環", "直前の操作結果を次の判断に使う。"], ["長い仕事", "セッションを越えて、進捗や検証済みの状態を復元する。"]], flow: ["結果", "記録", "取得", "再開"], boundary: "LLMがあらゆる会話を自動で永久に記憶するという意味ではない。保存範囲と更新規則を設計する。", sources: ["long"], related: ["long-running", "context", "harness"], slide: "harness" },
  { id: "tools", label: "Tools", title: "外部世界へ働きかける", category: "CONNECTION", date: "05", color: teal, position: [3, -.3, 3.5], summary: "検索、計算、ファイル編集、API、画面操作などを、アプリ側の実装で実行する。", facts: [["契約", "名前、入力形式、出力形式、実行権限を定義する。"], ["フィードバック", "成功、失敗、取得結果を次の判断へ戻す。"]], flow: ["引数", "検証", "実行", "結果"], boundary: "ツールがあるだけで自律的なAgentになるわけではない。使う順序を固定したWorkflowも有効。", sources: ["functions", "agents"], related: ["function-calling", "computer-use", "protocol"], slide: "agent" },
  { id: "protocol", label: "MCP", title: "接続のための共通プロトコル", category: "CONNECTION", date: "06", color: teal, position: [5, 1.3, 0], summary: "Host・Client・Serverを分け、ツールやデータを共通のインターフェースで公開する。", facts: [["Host / Client", "AIアプリがClientを管理し、Serverごとの接続を持つ。"], ["Server", "Tools、Resources、Promptsなどの機能を提供する。"]], flow: ["Host", "Client", "Server", "機能"], boundary: "MCPは任意の接続方式。Agentの判断ループや認可を代わりに実装するものではない。", sources: ["protocol", "mcp"], related: ["mcp-release", "tools", "harness"], slide: "mcp" },
  { id: "loop", label: "Agent loop", title: "結果から、次の一手へ", category: "CONTROL", date: "07", color: gold, position: [0, 3.7, -1.8], summary: "モデルの判断でツールや進め方を選び、環境からの結果をもとに次の動作を決める。", facts: [["循環", "判断 → 行動 → 観察 → 更新。必要に応じて人へ質問する。"], ["終了", "完了、上限到達、エラー、人への引き継ぎなどで止める。"]], flow: ["判断", "行動", "観察", "更新"], boundary: "AgentとWorkflowの境界には複数の定義がある。ここでは実行経路をモデルが動的に選ぶ構成をAgentと呼ぶ。", sources: ["agents", "react"], related: ["react-loop", "model", "evaluation"], slide: "agent" },
  { id: "harness", label: "Harness", title: "実行を支える基盤", category: "ENGINEERING", date: "08", color: gold, position: [0, -2, 0], summary: "モデルとツールをつなぎ、状態、権限、実行環境、ログ、検証を扱う周辺システム。", facts: [["実行環境", "利用できるツールやファイル、隔離された実行場所を用意する。"], ["信頼性", "記録、回復、再試行、停止の仕組みを整える。"]], flow: ["指示・状態", "実行", "記録", "検証"], boundary: "Harnessは製品や組織によって範囲が異なる実践概念。図の区分はこの資料の整理で、標準規格ではない。", sources: ["harness", "long"], related: ["harness-practice", "memory", "evaluation"], slide: "harness" },
  { id: "evaluation", label: "Evals", title: "成果を確かめる", category: "ENGINEERING", date: "09", color: gold, position: [3, -.3, -3.5], summary: "テスト、観察可能な実行結果、レビューによって、定義した完了条件と品質を確かめる。", facts: [["実行中", "ツールの応答、テスト結果、途中状態を確認する。"], ["改善", "失敗例を記録し、指示、ツール、実行環境を修正する。"]], flow: ["成果物", "検証", "結果", "改善"], boundary: "自己評価だけで正しさを保証できない。用途に合った外部の検証基準と人のレビューを組み合わせる。", sources: ["harness", "codex"], related: ["loop", "oversight", "harness"], slide: "synthesis" },
  { id: "oversight", label: "Human control", title: "人が範囲と採否を決める", category: "CONTROL", date: "10", color: gold, position: [0, 3.5, 4], summary: "重要な操作の承認、権限の範囲、結果の採用や中断を、人が管理する。", facts: [["境界", "閲覧・下書き・送信などの操作を区別し、必要な権限だけを渡す。"], ["介入", "不確実な状態で質問・承認・引き継ぎへ移れるようにする。"]], flow: ["提案", "確認", "承認・中断"], boundary: "図の接続は情報や制御の関係を表す。すべてのAgentが同一の10部品を持つという意味ではない。", sources: ["functions", "agents"], related: ["goal", "tools", "evaluation"], slide: "synthesis" },
];

export const atlasNodes = [...evolutionNodes, ...architectureNodes];
export const architectureEdges: [string, string][] = [["goal", "model"], ["context", "model"], ["memory", "context"], ["model", "tools"], ["tools", "protocol"], ["model", "loop"], ["loop", "evaluation"], ["evaluation", "model"], ["harness", "model"], ["harness", "memory"], ["harness", "tools"], ["oversight", "loop"]];
