"use client";
import { useState, type CSSProperties } from "react";
import { useRunner } from "./LabControls";
import { Scene, Playback } from "./SceneControls";

export function CostScene() {
  const [saving,setSaving]=useState(60),[destination,setDestination]=useState(1);
  const freed=Math.round(60*saving/100), total=100-freed;
  return <Scene name="プロトタイプの工数" className="cost-scene"><div className="cost-equation"><div><span>BEFORE</span><b>100</b></div><i>→</i><div><span>AI ASSISTED</span><b>{total}</b></div><div className="cost-delta"><span>余力</span><strong>＋{freed}</strong></div></div><div className="cost-factories">{[false,true].map(ai=><div className="cost-factory" key={String(ai)}><span>{ai?"AI":"BASELINE"}</span><div className="cost-pipeline"><div className="cost-block cost-spec" style={{flex:20}}><b>20</b><small>設計</small></div><div className="cost-block cost-build" style={{flex:ai?60-freed:60}}><b>{ai?60-freed:60}</b><small>実装</small></div><div className="cost-block cost-verify" style={{flex:20}}><b>20</b><small>検証</small></div>{ai&&<div className="cost-freed" style={{flex:freed}}><span>＋{freed}</span><i>↘</i></div>}</div></div>)}</div><div className="cost-dial"><span>AI支援</span><input type="range" min="0" max="85" step="5" value={saving} onChange={event=>setSaving(Number(event.target.value))} aria-label="実装工数の削減率"/><output>{saving}%</output><small>相対工数 · 仮定</small></div><div className="investment-stream" aria-hidden="true">{Array.from({length:Math.ceil(freed/3)},(_,index)=><i key={index} style={{"--token":index,"--destination":destination} as CSSProperties}/>)}</div><div className="investment-targets" role="group" aria-label="余力の配分">{["顧客理解","検証","反復"].map((label,index)=><button type="button" key={label} aria-pressed={destination===index} onClick={()=>setDestination(index)}><span>{["◎","✓","↻"][index]}</span><b>{label}</b><output>＋{destination===index?freed:0}</output></button>)}</div></Scene>;
}

export function SprintScene({active}:{active:boolean}) {
  const [fault,setFault]=useState(false),[flipped,setFlipped]=useState(false);
  const runner=useRunner(active,90,150);
  const minute=runner.step;
  const phase=minute<15?0:minute<55?1:minute<75?2:minute<85?3:4;
  const failing=fault&&phase===3;
  return <Scene name="90分の制作サイクル" className="sprint-scene"><div className="sprint-stage"><div className="sprint-timepiece" style={{"--time":`${minute*4}deg`} as CSSProperties}><div><strong>{String(minute).padStart(2,"0")}</strong><span>/ 90 MIN</span></div><small>{["SPEC","BUILD","INTEGRATE","QA","PLAYTEST"][phase]}</small></div><div className="sprint-workbench" data-phase={phase} data-failing={failing}><div className="workbench-files"><span data-ready={minute>=15}>rules.md <i>{minute>=15?"✓":"…"}</i></span><span data-ready={minute>=55}>game.ts <i>{minute>=55?"✓":"…"}</i></span><span data-ready={minute>=55}>card.svg <i>{minute>=55?"✓":"…"}</i></span><span data-ready={minute>=55}>deck.json <i>{minute>=55?"✓":"…"}</i></span></div><div className="sprint-game-preview"><div className="sprint-window-dots"><i/><i/><i/></div><button type="button" aria-label="制作中のカードをめくる" className="sprint-playing-card" disabled={minute<55} aria-pressed={flipped} onClick={()=>setFlipped(value=>!value)} data-flipped={flipped}><span>{flipped?"一つだけ、選ぶ。":"✦"}</span></button><div className="sprint-test-result" role="status">{minute<55?"BUILDING":failing?"FAIL / DUPLICATE ACTION":phase===4?fault?"RETEST ✓":"PLAYTEST ✓":"BUILD ✓"}</div></div></div><div className="sprint-deliverables">{["SPEC","CODE","ART","CONTENT","BUILD","TEST"].map((label,index)=><span key={label} data-done={minute>=[15,55,55,55,75,85][index]}><i>{minute>=[15,55,55,55,75,85][index]?"✓":"○"}</i>{label}</span>)}<button type="button" aria-pressed={fault} onClick={()=>{setFault(value=>!value);runner.seek(75);}} aria-label="QAエラーを切り替え">QA {fault?"×":"✓"}</button></div></div><div className="sprint-score"><div className="sprint-score-phases">{[["SPEC",0,15],["PARALLEL",15,55],["INTEGRATE",55,75],["QA",75,85],["PLAY",85,90]].map(([label,start,end])=><button type="button" key={label} style={{flex:Number(end)-Number(start)}} aria-label={`${label} ${start}分`} aria-pressed={minute>=Number(start)&&minute<Number(end)} onClick={()=>runner.seek(Number(start))}>{label}</button>)}</div><input type="range" min="0" max="90" value={minute} onChange={event=>runner.seek(Number(event.target.value))} aria-label="制作時間"/><div className="sprint-score-ticks"><span>00</span><span>15</span><span>30</span><span>45</span><span>60</span><span>75</span><span>90</span></div></div><Playback runner={runner} scrub={false}/></Scene>;
}
